- name: Alpine-maintain
  hosts: alpine
  tasks:
  - name: Update-and-upgrade
    apk:
     update_cache: true
     upgrade: true
    become: true

  - name: K3s-running
    service:
     name: k3s
     enabled: true
     state: started
    become: true
