# Third part of the installer, fixing up things, installing guest agent, pip, vim and htop
# Made for Alpine 3.18-r0 Standard, millage may vary

# You will need to add the host with the correct anible_host, anible_user and ansible_become_pass within the alpine group in your host.yml
# If you are writing the host.yml from hand make sure to set ansible_become_method: doas as well

# Your host.yml should look like this
# alpine:
# children:
#   test:
#     ansible_host: 192.168.1.X
#     ansible_user: "YourUser"
#     ansible_become_pass: "YourPassword"
#     ansible_python_interpreter: auto_silent
#     ansible_become_method: doas

# After this you can go over to installing k3s
# either adding it to an existing cluster with k3s-node-install.yml
# or spinning up a new one with k3s-primary-deploy.yml

- name: Final-Setup
  hosts: alpine
  tasks:
  - name: Ssh-demon-disabled-password-authentication
    ansible.builtin.template:
      src: ../templates/sshd_config
      dest: /etc/ssh/sshd_config
    become: true

  - name: Ssh-Reboot
    ansible.builtin.service:
      name: sshd
      enabled: true
      state: restarted
    become: true

  - name: Disable-Root-Login
    ansible.builtin.command: # ansible.builtin.user with password_lock seems to not work
      cmd: "passwd -l root"
    become: true
    ignore_errors: true # If already disabled the command will bounce

  - name: Write-Motd
    ansible.builtin.copy:
      src: ../templates/motd
      dest: /etc/motd
    become: true

  - name: Update-and-upgrade
    community.general.apk:
      update_cache: true
      upgrade: true
    become: true

  - name: Guest-agent-install
    community.general.apk:
      name: qemu-guest-agent
      state: present
    become: true

  - name: Guest-agent-start
    ansible.builtin.service:
      name: qemu-guest-agent
      enabled: true
      state: started
    become: true

  - name: Pip-install
    community.general.apk:
      name: py3-pip
      state: present
    become: true

  - name: Vim-install
    community.general.apk:
      name: vim  # or take nano, your pick
      state: present
    become: true

  - name: Htop
    community.general.apk:
      name: htop
      state: present
    become: true

  - name: Neofetch-because-cool
    community.general.apk:
      name: neofetch
      state: present
    become: true