- name: Alpine-Maintain
  hosts: alpine
  tasks:
  - name: Update-and-upgrade
    community.general.apk:
     update_cache: true
     upgrade: true
    become: true

- name: K3s-Maintain
  hosts: kube
  tasks:
  - name: K3s-running
    service:
     name: k3s
     enabled: true
     state: started
    become: true
